sudo: required
dist: trusty

language: go

go:
  - 1.6
  - 1.7
  - tip

os:
  - linux
#  - osx

matrix:
  allow_failures:
  - go: 1.6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libxxf86vm-dev
      - libnotify-dev
      - libgtk2.0-dev
      - libpango1.0-dev
      - libatk1.0-dev
      
      
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then free -m; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90; fi

script:
  - gcc --version
  - g++ --version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ld --version; fi
  - travis_wait 50 go get -t -v -x ./...
  - travis_wait 50 GOARCH=386 go get -t -v -x ./...
  
